theme: jekyll-theme-time-machine
title: Taking a wrong turn on the internet there, Friendo.
description: my name is Kelvin Aggerholm, but i also answer to the title of "hey asshole" and "i don´t care just give me a hotdog". That last one is optional.
